CLASS zvks_cl_csvuploadmasteraux DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zvks_cl_csvuploadmasteraux IMPLEMENTATION.
ENDCLASS.
